// Generated by CoffeeScript 1.6.3
var total_lang_array  = new Array("en","cn");
var disp_lang_array   = new Array("en","cn");
var during_break = false;
var during_playing = false;
var disp_lang_indi = 3;
function playVideo() {
    player.playVideo();
}
function pauseVideo() {
    player.pauseVideo();
}
function seekTo(s) {
    player.seekTo(s);
}
function currentTime() {
    return player.currentTime();
}

function subtitle_getjson(jsonfile, lang) {
    var json_result;
    return json_result = $.getJSON(jsonfile, function (data) {
        $.each(data, function (i, item) {
            eval("sub_start_" + lang + ".push(item.start)");
            eval("sub_text_" + lang + ".push(item.text)");
            eval("sub_end_" + lang + ".push(item.end)");
            return eval("sub_index_" + lang + ".push(Math.floor(item.start / 1000))");
        });
        return eval("sub_json_" + lang + "=this.json_result");
    });
}

function remove_disp_lang_inArray(e){
    var t, _ref;
    if ((t = disp_lang_array.indexOf(e)) > -1) {
        return ([].splice.apply(disp_lang_array, [t, t - t + 1].concat(_ref = [])), _ref);
    }
}



$(document).ready(function () {
    $('.btn-en').on('click', function () {
        if ($(this).hasClass('btn-success')) {
            disp_lang_indi = ~(~disp_lang_indi | 1);
            $('.srt_asset').find('.srt-en').remove();
            remove_disp_lang_inArray("en");
        }
        else {
            disp_lang_indi |= 1;
            $('.srt_asset').prepend('<div class="srt-en"></div>');
            disp_lang_array.push("en");
        }

        $(this).toggleClass('btn-success');
    });


    $('.btn-cn').on('click', function () {
        if ($(this).hasClass('btn-success')) {
            disp_lang_indi = ~(~disp_lang_indi | 2);
            $('.srt_asset').find('.srt-cn').remove();
            remove_disp_lang_inArray("cn");
        }
        else {
            disp_lang_indi |= 2;
            $('.srt_asset').find('.sub-btn').before('<div class="srt-cn"></div>');
            disp_lang_array.push("cn");
        }

        $(this).toggleClass('btn-success');

    });
});
/*
 //@ sourceMappingURL=subtitle_player_js.map
 */
