// Generated by CoffeeScript 1.6.3
(function() {
  var currentTime, pauseVideo, playVideo, seekTo, subtitle_getjson;

  pauseVideo = function() {
    return player.pauseVideo();
  };

  seekTo = function(s) {
    return player.seekTo(s);
  };

  playVideo = function() {
    return player.playVideo();
  };

  currentTime = function() {
    return player.currentTime();
  };

  subtitle_getjson = function(jsonfile, lang) {
    var json_result;
    return json_result = $.getJSON(jsonfile, function(data) {
      $.each(data, function(i, item) {
        eval("sub_start_" + lang + ".push(item.start)");
        eval("sub_text_" + lang + ".push(item.text)");
        eval("sub_end_" + lang + ".push(item.end)");
        return eval("sub_index_" + lang + ".push(Math.floor(item.start / 1000))");
      });
      return eval("sub_json_" + lang + "=this.json_result");
    });
  };

}).call(this);

/*
//@ sourceMappingURL=subtitle_player_js.map
*/
